# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:

    runs-on: ubuntu-latestruns-on:${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
   
   
    steps:
    - uses: actions/checkout@v2	
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
		pip install external\okta-0.0.3.1-py2.py3-none-any.whl
		pip install -e .
		pip install -e .[test]
		pip install -e .[setup]

    - name: Test with pytest
      run: |
        pytest
